import express from "express"
import path from "path"
import fs from "fs"

import React from 'react'
import { StaticRouter } from 'react-router-dom'
import { renderToString } from 'react-dom/server'
import { createStore, applyMiddleware } from 'redux'
import { Provider } from 'react-redux'
import App from '../src/App'


// client Side Root App ( Virtual Dom )
import routes from '../src/routes'
import reducers from '../src/store/reducers'
import reduxThunk  from "redux-thunk"
import Axios from "axios";

import { ChunkExtractor } from '@loadable/server'

// This is the stats file generated by webpack loadable plugin

const app = express()
app.use(express.static("build"));
app.use(express.json())


// only for development server............
import devServer from './devServer'
devServer(app)


const webStats = path.resolve('./build/static/loadable-stats.json')

app.get("*", (req, res) => {  

  const axiosInstance = Axios.create({
    baseURL :"http://localhost:4000",
    headers: { "cookie": req.get("cookie") || '' }
  })
  

  const store = createStore(reducers, {}, applyMiddleware(reduxThunk.withExtraArgument(axiosInstance)));

  const webExtractor = new ChunkExtractor({ statsFile: webStats })
  const jsx = webExtractor.collectChunks(
    <Provider store={store}>
      <StaticRouter location={req.url} context={{}} >
        <App/>
      </StaticRouter>
    </Provider>
  )
  const content = renderToString(jsx)

  // res.render("index.ejs")
  // return 
  res.send(`
    <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="themes" content="#f43454">
        <title>Server Side Rendering</title>
        ${webExtractor.getLinkTags()}
        ${webExtractor.getStyleTags()}
      </head>
      <body>
        <div id="backdrop"></div>
        <div id="modal-root"></div>
        <div id="root">${content}</div>
       
        ${webExtractor.getScriptTags()}

        <script src="//localhost:35729/livereload.js?snipver=1" async="" defer=""></script>
      </body>
    </html>
  `)
});


app.listen(4000, () =>
  console.log(`server a is running http://localhost:4000`)
);

      